### ISSUE TITLE
Function checkConnection

### ISSUE THREAD

**Issue by Pertti2012** [Mariusmssj/harbour-vlc-remote#2]
I downloaded your code to find out, how this kind a remote controller can be implemented.

I got a problem with checkConnection, which sometimes seemed to work but sometimes not. I thought the reason could be in function checkConnection in file SecondPage.qml, because there is the same function also in javascript file checkConnection.js. However the real reason was ip port conflict between VLC and SailfisOD SDK. Both are using port 8080.

Anyway I removed checkConnection.js and commented out import of checkConnection.js in the qml code.

It seems, that ipport in VLC-player is fixed to 8080 for http. For Telnet remote control the port can be selected.

BTW, could the upTimer be stopped in Cover mode?

**Comment by Mariusmssj** [comment]
Hi, 
yeah the upTimer can be stopped because it just calls the function on the firstpage.qml "function sendCommand(command)"

Sorry about the code being really messy it was my first time working with QML and such. Also I ran into xml issues with getting information back from VLC host, thus the elaborate usage of timers everywhere.

If anything else is confusing you let me know.
